version: 2

sources:
  - name: dbsales
    database: dbsales_5qef 
    schema: public              
    tables:
      - name: commodities        
        description: "Raw commodities data"
        columns:
          - name: Date
            description: "Date of commodity price"
          - name: ClosingValue
            description: "Closing price value"
          - name: Commodity
            description: "Type of commodity"

      - name: trading_data        
        description: "Raw Insetion of the trading data csv"
        columns:
          - name: Date
            description: "Date of commodity price"
          - name: Commodity
            description: "Type of commodity"  
          - name: Action
            description: "Action: buy or sell the commodity"
          - name: Qauntity
            description: "Quantity for the sell or buy"
          